# Generated by Django 5.0.4 on 2024-05-01 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listcompramateriapr',
            name='id_materia_prima',
        ),
        migrations.RemoveField(
            model_name='listcompramateriapr',
            name='id_proveedor',
        ),
        migrations.DeleteModel(
            name='TEmpresa',
        ),
        migrations.DeleteModel(
            name='TFabrica',
        ),
        migrations.DeleteModel(
            name='TFormulas',
        ),
        migrations.DeleteModel(
            name='TMateriaPrima',
        ),
        migrations.DeleteModel(
            name='ListCompraMateriaPr',
        ),
        migrations.DeleteModel(
            name='TProveedor',
        ),
    ]
