# Generated by Django 5.0.4 on 2024-05-01 03:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0002_remove_listcompramateriapr_id_materia_prima_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TEmpresa',
            fields=[
                ('id_empresa', models.IntegerField(primary_key=True, serialize=False)),
                ('empresa', models.CharField(max_length=45)),
                ('cuit', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 't_empresa',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TFabrica',
            fields=[
                ('id_fabrica', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha_fabricacion', models.CharField(blank=True, max_length=50, null=True)),
                ('granja_fabricacion', models.IntegerField(blank=True, null=True)),
                ('codigo_formula', models.IntegerField(blank=True, null=True)),
                ('kilos_fabricados', models.IntegerField(blank=True, null=True)),
                ('precio_costo', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 't_fabrica',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TFormulas',
            fields=[
                ('id_formula', models.IntegerField(primary_key=True, serialize=False)),
                ('tipo_formula', models.IntegerField(blank=True, null=True)),
                ('pienso', models.CharField(blank=True, max_length=45, null=True)),
                ('materia_prima', models.CharField(blank=True, max_length=45, null=True)),
                ('id_materia_prima', models.IntegerField(blank=True, null=True)),
                ('kilos', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('precio', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fabricper', models.IntegerField(blank=True, db_column='FABRICPER', null=True)),
                ('fabricacu', models.IntegerField(blank=True, db_column='FABRICACU', null=True)),
                ('impperiod', models.DecimalField(blank=True, db_column='IMPPERIOD', decimal_places=2, max_digits=10, null=True)),
                ('impacum', models.DecimalField(blank=True, db_column='IMPACUM', decimal_places=2, max_digits=10, null=True)),
                ('control', models.CharField(blank=True, db_column='CONTROL', max_length=45, null=True)),
            ],
            options={
                'db_table': 't_formulas',
                'db_table_comment': '\t',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TMateriaPrima',
            fields=[
                ('id_materia_prima', models.IntegerField(primary_key=True, serialize=False)),
                ('materia_prima', models.CharField(blank=True, max_length=45, null=True)),
                ('precio', models.DecimalField(blank=True, decimal_places=4, max_digits=50, null=True)),
                ('precio_almacen', models.DecimalField(blank=True, decimal_places=4, max_digits=50, null=True)),
                ('cantidad_inicial', models.DecimalField(blank=True, decimal_places=0, max_digits=50, null=True)),
                ('cantidad_actual', models.DecimalField(blank=True, decimal_places=0, max_digits=50, null=True)),
                ('entrada_periodo', models.DecimalField(blank=True, decimal_places=0, max_digits=50, null=True)),
                ('entrada_acumulada', models.DecimalField(blank=True, decimal_places=0, max_digits=50, null=True)),
                ('entrada_impuesto_periodo', models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True)),
                ('entrada_impuesto_acumulado', models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True)),
                ('existencia_real', models.DecimalField(blank=True, decimal_places=0, max_digits=50, null=True)),
                ('salidas_periodo', models.DecimalField(blank=True, decimal_places=0, max_digits=50, null=True)),
                ('salidas_acumuladas', models.DecimalField(blank=True, decimal_places=0, max_digits=50, null=True)),
                ('salidas_impuesto_periodo', models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True)),
                ('salidas_impuesto_acumuladas', models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True)),
                ('diferencia_materia_prima', models.DecimalField(blank=True, decimal_places=0, max_digits=50, null=True)),
                ('impuesto_diferencia_materia_prima', models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True)),
            ],
            options={
                'db_table': 't_materia_prima',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TProveedor',
            fields=[
                ('id_proveedor', models.IntegerField(primary_key=True, serialize=False)),
                ('proveedor', models.CharField(blank=True, max_length=45, null=True)),
                ('direccion', models.CharField(blank=True, max_length=45, null=True)),
                ('puntos', models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True)),
                ('iva', models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True)),
                ('localidad', models.CharField(blank=True, max_length=45, null=True)),
                ('provincia', models.CharField(blank=True, max_length=45, null=True)),
                ('codigo_postal', models.CharField(blank=True, max_length=45, null=True)),
                ('cuit', models.CharField(blank=True, max_length=45, null=True)),
                ('telefono', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 't_proveedor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ListCompraMateriaPr',
            fields=[
                ('id_compra', models.IntegerField(primary_key=True, serialize=False)),
                ('materia_prima', models.TextField(max_length=200)),
                ('proveedor', models.TextField(max_length=200)),
                ('cantidad', models.IntegerField()),
                ('importe', models.DecimalField(decimal_places=4, max_digits=10)),
                ('stock_actual', models.IntegerField()),
                ('fecha_compra', models.DateTimeField(auto_now_add=True)),
                ('id_materia_prima', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.tmateriaprima')),
                ('id_proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.tproveedor')),
            ],
            options={
                'db_table': 't_listcompmatpr',
            },
        ),
    ]
